services:
  conversion:
    image: rust:1.82
    volumes:
      - ./server1:/code
    working_dir: /code
    entrypoint: cargo
    command: run
    ports:
      - '8080:8080'

  pricing:
    image: rust:1.82
    volumes:
      - ./server2:/code
    working_dir: /code
    entrypoint: cargo
    command: run
    ports:
      - '8081:8081'

  claims:
    build: server3
    volumes:
      - ./server3:/code
    working_dir: /code
    entrypoint: /code/entrypoint.sh
    ports:
      - '8082:8082'

  router:
    image: ghcr.io/wundergraph/cosmo/router:sha-292d7e4
    # https://cosmo-docs.wundergraph.com/router/configuration
    environment:
      EXECUTION_CONFIG_FILE_PATH: "router.json"
      EXECUTION_CONFIG_FILE_WATCH: true
      GRAPH_API_TOKEN: ""
      LISTEN_ADDR: "0.0.0.0:3002"
      LOG_LEVEL: debug
      DEV_MODE: true
      PLAYGROUND_ENABLED: true
      PLAYGROUND_PATH: "/playground"
      GRAPHQL_METRICS_ENABLED: false
      PROMETHEUS_ENABLED: false
    depends_on:
      - conversion
      - pricing
      - claims
    volumes:
      - ./router/config.yaml:/config.yaml
      - ./router/router.json:/router.json
    ports:
      - '3002:3002'

  schema:
    build: router
    volumes:
      - ./router:/code
    depends_on:
      - conversion
      - pricing
      - claims
    working_dir: /code
