[package]
name = "server1"
version = "0.1.0"
edition = "2021"

[lib]
name = "server1"
path = "src/lib.rs"

[dependencies]
actix-web = "3.3.2"
async-graphql = { version = "2.11.3", features = ["log"] }
async-graphql-actix-web = "2.11.3"
env_logger = "0.9.0"
